substitutions:
  devicename: airfryer
  friendly_name: Airfryer
  device_description: Airfryer Proscenic T21
  
# Translate following vars to get labels in your language
  lbl_restart: "Riavvio"
  lbl_esphome_version: "Versione ESPHome"
  lbl_airfyer_status: "Stato friggitrice"
  lbl_on_off: "Accensione"
  lbl_start_pause: "Avvio/Pausa"
  lbl_keep_warm: "Tieni in caldo"
  lbl_start_delay: "Cottura programmata"
  lbl_remaining_time: "Tempo rimanente"
  lbl_current_cooking_temp: "Temperatura di cottura corrente"
  lbl_internal_temperature: "Temperatura interna"
  lbl_state_standby: "In standby"
  lbl_state_start_delay: "Cottura programmata"
  lbl_state_cooking: "In cottura"
  lbl_state_keep_warm: "Tieni in caldo"
  lbl_state_off: "Spenta"
  lbl_state_cooking_complete: "Cottura completata"
  lbl_tray_status: "Cassetto aperto"
  lbl_cooking_time: "Tempo di cottura"
  lbl_keep_warm_time: "Tieni in caldo per"
  lbl_cooking_delay_minutes: "Avvia cottura tra"
  lbl_cookbook: "Ricettario"
  lbl_recipe_noting: "Nessuna ricetta"
  lbl_recipe_fries: "Patatine"
  lbl_recipe_shrips: "Gamberi"
  lbl_recipe_pizza: "Pizza"
  lbl_recipe_chicken: "Pollo"
  lbl_recipe_fish: "Pesce"
  lbl_recipe_steak: "Bistecca"
  lbl_recipe_muffin: "Muffin"
  lbl_recipe_bacon: "Bacon"
  lbl_recipe_custom: "Cottura personalizzata"
  
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  power_save_mode: HIGH
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret wifi_password

captive_portal:

logger:
  level: DEBUG
  #tuya airfryer
  baud_rate: 0
  
api:
ota:

web_server:
  port: 80

time:
  - platform: sntp
    id: my_time

button:
  - platform: restart
    name: "${lbl_restart} ${devicename}"
    icon: mdi:restart
text_sensor:
  - platform: version
    name: "${lbl_esphome_version}"
  - platform: template
    name: "${lbl_airfyer_status}"
    id: airfryer_status
    icon: mdi:pot-mix-outline
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

switch:
  - platform: tuya
    name: "${lbl_on_off}"
    switch_datapoint: 1
    icon: mdi:power
  - platform: tuya
    name: "${lbl_start_pause}"
    switch_datapoint: 2
    icon: mdi:play-pause
  - platform: tuya
    name: "${lbl_keep_warm}"
    switch_datapoint: 104
    icon: mdi:pot-steam-outline
  - platform: tuya
    name: "${lbl_start_delay}"
    switch_datapoint: 106
    icon: mdi:calendar-clock
sensor:
  - platform: tuya
    name: "${lbl_remaining_time}"
    sensor_datapoint: 8
    icon: mdi:clock-end
  - platform: tuya
    name: "${lbl_current_cooking_temp}"
    sensor_datapoint: 103
    icon: mdi:thermometer
    # comment following two lines to get °F value
    filters:
      - lambda: return (x - 32) * 5 / 9;
    unit_of_measurement: "°C" # replace with °F if you use Fahrenheit scale

    # This sensor measure internal tray temperature. It updates only on power on/off
  - platform: tuya 
    name: "${lbl_internal_temperature}"
    sensor_datapoint: 107
    force_update: true
    icon: mdi:thermometer
    # uncomment following two lines to get °F value
#    filters:
#      - lambda: return (x * 9 / 5) + 32;
    unit_of_measurement: "°C" # replace with °F if you use Fahrenheit scale

  - platform: tuya
    id: numeric_airfryer_state
    sensor_datapoint: 5
    internal: true
    on_value:
      then:
        - lambda: |-
            if (x == 0) { id(airfryer_status).publish_state("${lbl_state_standby}"); } 
            else if (x == 1) { id(airfryer_status).publish_state("${lbl_state_start_delay}"); }
            else if (x == 2) { id(airfryer_status).publish_state("${lbl_state_cooking}"); }
            else if (x == 3) { id(airfryer_status).publish_state("${lbl_state_keep_warm}"); }
            else if (x == 4) { id(airfryer_status).publish_state("${lbl_state_off}"); }
            else if (x == 5) { id(airfryer_status).publish_state("${lbl_state_cooking_complete}"); }
            else { id(airfryer_status).publish_state("N/A"); }
binary_sensor:
  - platform: tuya
    name: "${lbl_tray_status}"
    sensor_datapoint: 102
    icon: mdi:toaster-oven
number:
  - platform: tuya
    name: "${lbl_cooking_time}"
    number_datapoint: 7
    min_value: 1
    max_value: 60
    step: 1
    icon: mdi:av-timer
  - platform: tuya
    name: "${lbl_keep_warm_time}"
    number_datapoint: 105
    min_value: 1
    max_value: 60
    step: 1
    icon: mdi:av-timer
  - platform: tuya
    name: "${lbl_cooking_delay_minutes}"
    number_datapoint: 6
    min_value: 5
    max_value: 720
    step: 1
    icon: mdi:av-timer

select:
  - platform: tuya
    name: "${lbl_cookbook}"
    enum_datapoint: 3
    optimistic: true
    icon: mdi:chef-hat
    options:
      0: ${lbl_recipe_noting}
      1: ${lbl_recipe_fries}
      2: ${lbl_recipe_shrips}
      3: ${lbl_recipe_pizza}
      4: ${lbl_recipe_chicken}
      5: ${lbl_recipe_fish}
      6: ${lbl_recipe_steak}
      7: ${lbl_recipe_muffin}
      8: ${lbl_recipe_bacon}
      10: ${lbl_recipe_custom}
